// Mocks generated by Mockito 5.0.16 from annotations
// in fakeslink/test/app/domain/use_cases/login_usecase_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:fakeslink/app/domain/entities/session.dart' as _i6;
import 'package:fakeslink/app/domain/repositories/authentication_repository.dart'
    as _i3;
import 'package:fakeslink/core/architecture/failure.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:multiple_result/multiple_result.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResult_0<E, S> extends _i1.Fake implements _i2.Result<E, S> {}

/// A class which mocks [AuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepository extends _i1.Mock
    implements _i3.AuthenticationRepository {
  MockAuthenticationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.Failure, _i6.Session>> logIn(
          String? username, String? password) =>
      (super.noSuchMethod(Invocation.method(#logIn, [username, password]),
              returnValue: Future<_i2.Result<_i5.Failure, _i6.Session>>.value(
                  _FakeResult_0<_i5.Failure, _i6.Session>()))
          as _i4.Future<_i2.Result<_i5.Failure, _i6.Session>>);
  @override
  _i4.Future<_i2.Result<_i5.Failure, _i6.Session>> logInWithFingerprint() =>
      (super.noSuchMethod(Invocation.method(#logInWithFingerprint, []),
              returnValue: Future<_i2.Result<_i5.Failure, _i6.Session>>.value(
                  _FakeResult_0<_i5.Failure, _i6.Session>()))
          as _i4.Future<_i2.Result<_i5.Failure, _i6.Session>>);
  @override
  _i4.Future<_i2.Result<_i5.Failure, void>> setUpFingerprintAuth(
          String? password) =>
      (super.noSuchMethod(Invocation.method(#setUpFingerprintAuth, [password]),
              returnValue: Future<_i2.Result<_i5.Failure, void>>.value(
                  _FakeResult_0<_i5.Failure, void>()))
          as _i4.Future<_i2.Result<_i5.Failure, void>>);
  @override
  String toString() => super.toString();
}
