# This is a basic workflow to help you get started with Actions

name: CI-CD

env:
  flutter_path: /opt/hostedtoolcache/flutter

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      job:
        description: 'Job to run manually'
        required: true
        default: 'build_ios'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Set up Flutter for all other tasks.
  setup:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ env.flutter_path }}
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.1'
          channel: 'stable'

  sync_dependencies:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Verify Dockerfile changed
        uses: tj-actions/verify-changed-files@v5.5
        id: changed_files
        with:
          files: |
             pubspec.yaml
      - name: Cache Flutter
        if: steps.changed_files.outputs.files_changed == 'true'
        id: cache-flutter
        uses: actions/cache@v1
        with:
          path: ${{ env.flutter_path }}
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v1
        if: steps.changed_files.outputs.files_changed == 'true'
        with:
          channel: 'stable'
          flutter-version: '2.10.1'
          
      - name: Run flutter pub get
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          flutter clean
          flutter pub get
          
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: ${{ env.flutter_path }}
          key: ${{ runner.os }}-flutter
  
  test:
    runs-on: ubuntu-20.04
    needs: sync_dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v1
        with:
          path: ${{ env.flutter_path }}
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.10.1'
      - name: run test
        run: flutter test --coverage

  build_android_apk:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    needs: sync_dependencies
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: build android
        run: flutter build apk
          
      - name: Archive apk artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app.apk
          path: |
            build/app/outputs/flutter-apk/app.apk
            
  build_ios:
    runs-on: ubuntu-20.04
    needs: sync_dependencies
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: build ios
        run: flutter build ios
          
      - name: Archive apk artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Dci.ipa
          path: build/ios/ipa/Dci.ipa
    
